services:
    app:
        container_name: wishlist-app
        image: ghcr.io/cmintey/wishlist
        ports:
            - 3280:3280
        volumes:
            - ./data:/usr/src/app/data
        env_file:
            - .env
